// swift-tools-version: 6.2

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Food Donation",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Food Donation",
            targets: ["FoodDonationApp"],
            bundleIdentifier: "com.linminpei.fooddonation",
            displayVersion: "0.1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .camera(purposeString: "Scan donated food barcodes and capture package evidence."),
                .localNetwork(purposeString: "Connect to the food donation development server on this network.", bonjourServiceTypes: []),
                .appTransportSecurity(configuration: .init(
                    allowsLocalNetworking: true,
                    exceptionDomains: [

                    ]
                )),
                .outgoingNetworkConnections()
            ]
        )
    ],
    dependencies: [
        .package(path: "..")
    ],
    targets: [
        .executableTarget(
            name: "FoodDonationApp",
            dependencies: [
                .product(name: "FoodDonationCore", package: "ios")
            ],
            path: "Sources"
        )
    ]
)
